{% set version = "0.0.13" %}
{% set sha256 = "f6efd434c4b0aa0ccf0156286197d9f26287418c49ea40ab3a73e4c7eb1af545" %}

package:
    name: scikit-beam
    version: {{ version }}

source:
    url: https://github.com/scikit-beam/scikit-beam/archive/v{{ version }}.tar.gz
    fn: scikit-beam-v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py build_ext -i
    - python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win or osx] 

requirements:
    build:
        - toolchain
        - python
        - setuptools
        - numpy 1.11.*
        - six
        - cython
        - autoconf    # [osx]
    run:
        - python
        - numpy >=1.11
        - scipy
        - six
        - xraylib
        - scikit-image
        - lmfit 0.8.3

test:
    imports:
        - skbeam
        - skbeam.io
        - skbeam.core
        - skbeam.core.accumulators
        - skbeam.core.constants
        - skbeam.core.fitting
        - skbeam.core.fitting.base
        - skbeam.ext
        - skbeam.core.fitting
        - skbeam.core.constants.xrf
        # has linux native library imports  # [not win]
        - skbeam.ext.ctrans    # [not win]
    commands:
        # Don't need to specify path due to the CONDA_DEFAULT_ENV env var being set inside of conda-build
        # which is pointing to the test environment
        # These next two lines are currently failing due to an API change from conda-build 1.21.* -> 2.0.*
        #- conda inspect linkages scikit-beam  # [not win]
        #- conda inspect objects scikit-beam  # [osx]

about:
    home: http://scikit-beam.github.io/scikit-beam/
    license: BSD 3-Clause
    summary: Data analysis algorithms for X-Ray, Neutron and Electron sciences
    # Need to add LICENSE to the manifest
    # license_file: LICENSE
    license_family: BSD

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
