{% set version = "0.0.9" %}

package:
    name: scikit-beam
    version: {{ version }}

source:
    url: https://github.com/scikit-beam/scikit-beam/archive/v{{ version }}.tar.gz
    fn: scikit-beam-v{{ version }}.tar.gz
    sha256: 2c149ccd25a1609b0cf1c1518b87b27b7e00ca4f60d502763f0222e4a80bd361

build:
  number: 0
  script:
    - python setup.py build_ext -i
    - python setup.py install --single-version-externally-managed --record=record.txt
  # v0.0.8 of scikit-beam is not windows compatible because the setup.py is not formatted correctly
  # to build the extensions that have some linux-specific include directives. Once there is a 0.0.9 tag,
  # we can remove thsi next line and be good to go
  skip: True  # [win]

requirements:
    build:
        - toolchain
        - python
        - setuptools
        - numpy x.x
        - six
        - cython
        - autoconf    # [osx]
    run:
        - python
        - numpy x.x
        - scipy
        - six
        - xraylib    # [not win]
        - scikit-image
        - lmfit 0.8.3

test:
    imports:
        - skbeam
        - skbeam.io
        - skbeam.core
        - skbeam.core.accumulators
        - skbeam.core.constants
        - skbeam.core.fitting
        - skbeam.core.fitting.base
        - skbeam.ext
        # xraylib is not conda installable on windows yet  # [not win]
        - skbeam.core.fitting    # [not win]
        - skbeam.core.constants.xrf    # [not win]
        # has linux native library imports  # [not win]
        - skbeam.ext.ctrans    # [not win]
    commands:
        - conda inspect linkages -n _test scikit-beam  # [not win]
        - conda inspect objects -n _test scikit-beam  # [osx]

about:
    home: http://scikit-beam.github.io/scikit-beam/
    license: BSD 3-Clause
    summary: Data analysis algorithms for X-Ray, Neutron and Electron sciences

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
