appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fLBpJDAv5i/N+Rl0kSAUnZXWthBbsjFd51RBHDnhVlK5aPOs7aqtGj3mZ94r/iugia0AGqiBIiRIcml/KLjJBofmCE3EeCW0Cyv4MSv7NBymCbBD6KvCCNMOXY26p07ytDfhC/Ynna7NYVIUTm6Cm2YdAA8jBErhHmKaRDQjAAgs6sRypnl5x8d/5zG9jS9X9MvYm1Pmypo79QSeCm6K8WIpmUfKSCI5PwEu6WpgwIlPK7axkJH1jCsf2Zt7XQ/skHhx6ac2SXuL52pJkWY5O9IeD6qlDuquwnbec0E7/IUC+EgVZtoXrA5p71IpTjEwMY7dwh+CSkCW369kAyUm5xgqWlcqMzLQi9iFkljWM5vug//Da3HknOphMC0hy9717ED6+/46oRdGqUONimzDuI84StmbRJavF53xoS6CDBN+P6JfjViDersXq+nMRaKU1dW8sZ9lWwp23Xu2TmiMr1LjOUJk8jGyzWp++/S6qYor6nsN0zK40na7yjPNwGERzFITU1zM7YBQr1lS8Y+NxJVe7PYKu9M+ACbyN2/TuaY632bFu7iwj+0p8iy4DtS/sgk4J/ydQrZgAVj6rTRm2juPV5/JXalLsZ9A2OtLYD/7WeUJ59eY/GVhl6m1CnV3E8UpiHTJDgxMN2yevfzPThlClgK4GwJ14IGUcleSdQ8=}
